[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 2 --threads 2 wsgi:app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1

[env]
PYTHONUNBUFFERED = "1"
DEBUG = "False"
