services:
  - type: web
    name: tts-application
    plan: free
    runtime: docker
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "False"
    disk:
      name: tts-data
      mountPath: /app
      sizeGB: 2
